---
  - name: login to OpenShift using provided token
    command: "oc login --insecure-skip-tls-verify=true --token {{ token }} {{ openshift_master_url }}"

  - name: "checking for Thoth Tiers"
    command: "oc get project {{ item }}"
    with_items:
      - "{{ THOTH_BACKEND_NAMESPACE  }}"
      - "{{ THOTH_MIDDLETIER_NAMESPACE }}"
      - "{{ THOTH_FRONTEND_NAMESPACE }}"
      - "{{ THOTH_INFRA_NAMESPACE }}"

  - name: "checking for Thoth Secrets"
    command: "oc get secret thoth --namespace {{ item }}"
    with_items:
      - "{{ THOTH_BACKEND_NAMESPACE  }}"
      - "{{ THOTH_MIDDLETIER_NAMESPACE }}"
      - "{{ THOTH_FRONTEND_NAMESPACE }}"

  - name: "checking for Thoth Config"
    command: "oc get configmap thoth --namespace {{ item }}"
    with_items:
      - "{{ THOTH_BACKEND_NAMESPACE  }}"
      - "{{ THOTH_MIDDLETIER_NAMESPACE }}"
      - "{{ THOTH_FRONTEND_NAMESPACE }}"

  - name: "checking for Thoth User API resources"
    command: "oc get {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - "template/user-api-deployment"
      - "template/user-api-buildconfig"
      - "imagestream/user-api"
      - "buildconfig/user-api"
      - "svc/user-api"
      - "deploymentconfig/user-api"

  - name: "checking for Thoth frontend CronJobs"
    command: "oc get cronjob {{ item }} --namespace {{ THOTH_FRONTEND_NAMESPACE }}"
    with_items:
      - "cleanup-job"
      - "package-releases"

  - name: "checking for required ImageStreams"
    command: "oc get {{ item }} --namespace {{ THOTH_BACKEND_NAMESPACE }}"
    with_items:
      - "imagestreams/python-36-centos7"  

  - name: "checking for Thoth Result API resources"
    command: "oc get {{ item }} --namespace {{ THOTH_MIDDLETIER_NAMESPACE }}"
    with_items:
      - "template/result-api-buildconfig"
      - "imagestreams/result-api"
      - "buildconfigs/result-api"
      - "svc/result-api"
      - "deploymentconfigs/result-api"

  - name: "checking for Thoth Backend CronJobs"
    command: "oc get cronjob graph-sync-job --namespace {{ THOTH_BACKEND_NAMESPACE }}"
